import type { PatientApplication } from "./types";

export const MOCK_APPLICATIONS: PatientApplication[] = [
  {
    id: "app-001",
    submittedAt: "2026-05-12T09:14:00Z",
    status: "READY_FOR_REVIEW",
    personal: {
      fullName: "Maria Elena Gutierrez",
      dob: "1985-03-14",
      address: "1421 Maple St, Greenville, SC 29601",
      phone: "(864) 555-0182",
      email: "m.gutierrez@email.com",
    },
    household: {
      householdSize: 4,
      dependents: 2,
      minors: 2,
    },
    financial: {
      incomeSources: ["Employment"],
      monthlyIncome: 2850,
      employmentStatus: "Full-time",
      insuranceStatus: "Uninsured",
    },
    documents: [
      {
        id: "doc-001a",
        type: "Photo ID",
        fileName: "drivers_license.jpg",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=ID",
        uploadedAt: "2026-05-12T09:10:00Z",
      },
      {
        id: "doc-001b",
        type: "Proof of Income",
        fileName: "pay_stub_april.pdf",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=PDF",
        uploadedAt: "2026-05-12T09:12:00Z",
      },
      {
        id: "doc-001c",
        type: "Proof of Residency",
        fileName: "utility_bill.pdf",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=PDF",
        uploadedAt: "2026-05-12T09:13:00Z",
      },
    ],
    missingDocumentsCount: 0,
    missingRequiredFields: [],
  },
  {
    id: "app-002",
    submittedAt: "2026-05-12T10:42:00Z",
    status: "INCOMPLETE_APPLICATION",
    personal: {
      fullName: "James Terrell Washington",
      dob: "1972-11-28",
      address: "302 Oak Ave, Apt 4B, Greenville, SC 29605",
      phone: "(864) 555-0341",
    },
    household: {
      householdSize: 1,
      dependents: 0,
    },
    financial: {
      incomeSources: ["Disability Benefits", "Part-time Employment"],
      monthlyIncome: 1200,
      employmentStatus: "Part-time",
      insuranceStatus: "Medicaid (Pending)",
    },
    documents: [
      {
        id: "doc-002a",
        type: "Photo ID",
        fileName: "state_id.jpg",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=ID",
        uploadedAt: "2026-05-12T10:38:00Z",
      },
      {
        id: "doc-002b",
        type: "Proof of Income",
        fileName: "",
        uploadStatus: "missing",
      },
    ],
    missingDocumentsCount: 1,
    missingRequiredFields: ["Proof of Income", "Insurance documentation"],
  },
  {
    id: "app-003",
    submittedAt: "2026-05-12T11:05:00Z",
    status: "NEEDS_FOLLOW_UP",
    personal: {
      fullName: "Priya Anand",
      dob: "1991-07-04",
      address: "89 Birchwood Dr, Greenville, SC 29615",
      phone: "(864) 555-0619",
      email: "p.anand@email.com",
    },
    household: {
      householdSize: 3,
      dependents: 1,
      minors: 1,
    },
    financial: {
      incomeSources: ["Self-employment"],
      monthlyIncome: 3400,
      employmentStatus: "Self-employed",
      insuranceStatus: "Uninsured",
    },
    documents: [
      {
        id: "doc-003a",
        type: "Photo ID",
        fileName: "passport.jpg",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=ID",
        uploadedAt: "2026-05-12T11:00:00Z",
      },
      {
        id: "doc-003b",
        type: "Proof of Income",
        fileName: "tax_return_2025.pdf",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=PDF",
        uploadedAt: "2026-05-12T11:01:00Z",
      },
      {
        id: "doc-003c",
        type: "Proof of Residency",
        fileName: "",
        uploadStatus: "missing",
      },
    ],
    missingDocumentsCount: 1,
    missingRequiredFields: ["Proof of Residency"],
  },
  {
    id: "app-004",
    submittedAt: "2026-05-11T14:30:00Z",
    status: "READY_FOR_REVIEW",
    personal: {
      fullName: "DeShawn Marcus Hill",
      dob: "2001-02-17",
      address: "555 River Rd, Greenville, SC 29601",
      phone: "(864) 555-0807",
      email: "dhill@email.com",
    },
    household: {
      householdSize: 2,
      dependents: 0,
    },
    financial: {
      incomeSources: ["Employment"],
      monthlyIncome: 1950,
      employmentStatus: "Full-time",
      insuranceStatus: "Uninsured",
    },
    documents: [
      {
        id: "doc-004a",
        type: "Photo ID",
        fileName: "drivers_license.jpg",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=ID",
        uploadedAt: "2026-05-11T14:20:00Z",
      },
      {
        id: "doc-004b",
        type: "Proof of Income",
        fileName: "pay_stub.pdf",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=PDF",
        uploadedAt: "2026-05-11T14:25:00Z",
      },
      {
        id: "doc-004c",
        type: "Proof of Residency",
        fileName: "lease_agreement.pdf",
        uploadStatus: "uploaded",
        thumbnailUrl: "https://placehold.co/80x60/e2e8f0/64748b?text=PDF",
        uploadedAt: "2026-05-11T14:27:00Z",
      },
    ],
    missingDocumentsCount: 0,
    missingRequiredFields: [],
  },
  {
    id: "app-005",
    submittedAt: "2026-05-11T16:12:00Z",
    status: "INCOMPLETE_APPLICATION",
    personal: {
      fullName: "Rosa Carmen Delgado",
      dob: "1968-09-22",
      address: "",
      phone: "(864) 555-0223",
    },
    household: {
      householdSize: 5,
      dependents: 3,
      minors: 3,
    },
    financial: {
      incomeSources: ["Seasonal Employment", "SNAP Benefits"],
      monthlyIncome: 1650,
      employmentStatus: "Seasonal",
      insuranceStatus: "Children on CHIP",
    },
    documents: [
      {
        id: "doc-005a",
        type: "Photo ID",
        fileName: "",
        uploadStatus: "missing",
      },
      {
        id: "doc-005b",
        type: "Proof of Income",
        fileName: "",
        uploadStatus: "missing",
      },
      {
        id: "doc-005c",
        type: "Proof of Residency",
        fileName: "",
        uploadStatus: "missing",
      },
    ],
    missingDocumentsCount: 3,
    missingRequiredFields: ["Address", "Photo ID", "Proof of Income", "Proof of Residency"],
  },
];
